#!/bin/bash

if [ "$(id -u)" != "0" ]; then
  echo "Please run as root"
  exit 1
fi

if ! ip -o link show | awk -F': ' '{print $2}' | grep -q "mon"; then
    airmon-ng start wlx00c0ca58b82f
fi

cd /home/pi/Code/rasmon
./monitor.py -i mon0 --mac-info --ssid --rssi --delimiter "~"
