#! /bin/sh
# /etc/init.d/rasmon

### BEGIN INIT INFO
# Provides:          rasmon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       Starts capturing probe frames.
### END INIT INFO

case "$1" in
  start)
    echo "Starting rasmon"
    # run application you want to start
    /home/pi/Code/rasmon/rasmon > /home/pi/Code/rasmon/logs/init.d_log &
    ;;
  stop)
    echo "Stopping rasmon"
    # kill application you want to stop
    kill -9 `ps -aux | grep rasmon | grep -v grep | awk '{ print $2 }'`
    ;;
  *)
    echo "Usage: /etc/init.d/rasmon {start|stop}"
    exit 1
    ;;
esac

exit 0

